# SPDX-FileCopyrightText: 2019 The cython-linux-usbmon Authors
#
# SPDX-License-Identifier: Apache-2.0

dist: xenial

language: python

matrix:
  include:
    - python: 3.8
      env: PYTEST_OPTIONS="--mypy"

install:
  # Make sure cython is installed to have the wheel built correctly.
  - pip install cython
  - pip install .[dev]

script:
  - pytest -vvv $PYTEST_OPTIONS
